spring:
  jackson.deserialization.fail-on-unknown-properties: false
  groovy.template.check-template-location: false

rest.api.version: 1.0
city.finding.service.url: "http://api.openweathermap.org/data/2.5/weather"

metrics.path:
  country: pl
  app: loan-application-decision-maker
  environment: prod

stubrunner.stubs:
  repository.root: "http://nexus.hackathon.dev.4finance.net:8081/nexus/content/repositories/releases/"
  group: com.ofg
  module: stub-definitions

graphite:
    host: "graphite.hackathon.dev.4finance.net"
    port: 2003
    
server.port: 8052
